version: 2

jobs:
  publish:
    docker:
      - image: docker:stable
    steps:
      - checkout
      - setup_remote_docker
      - run: |
          docker login -u $DOCKER_LOGIN -p $DOCKER_ACCESS_TOKEN \
          && ./publish.sh

workflows:
  version: 2

  # Build on push
  on_push:
    jobs:
      - publish:
          context: Docker Hub dbrgn
          filters:
            branches:
              only:
                - main

  # Build main branch every week on Sunday at 13:37
  weekly:
    triggers:
      - schedule:
          cron: "37 13 * * 1"
          filters:
            branches:
              only:
                - main
    jobs:
      - publish:
          context: Docker Hub dbrgn
